# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b40c1ecda9e46c64fae95bffcc3c00c024c4ddd8dbdf28425fdba169100dc92da259a73043e7398e52093422f6d082d63855653ac67df80247b144411b0b9f9

test:
  secret_key_base: 3410ec7120f97e14b00093b7dc2f5d0ee3a2007163369847223bda423c8a952ebcc956c64325a78fb25fceefb02237cda19598b53c95d1a2c94988cfebc7ca28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
